server:
  port: 8083

spring:
  application:
    name: transaction-streams
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: advanced-transaction-processor
      properties:
        processing.guarantee: exactly_once_v2
        num.stream.threads: 3
        cache.max.bytes.buffering: 10485760
        commit.interval.ms: 1000
