server:
  port: 8084

spring:
  application:
    name: transaction-logger
  datasource:
    url: jdbc:postgresql://220.133.201.243:5555/bank_simulation
    username: root
    password: audi51407088
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: logger-consumer
      auto-offset-reset: earliest 