server:
  port: 8081
  ssl:
    enabled: false
  http2:
    enabled: false

spring:
  application:
    name: transaction-producer
  datasource:
    url: jdbc:postgresql://220.133.201.243:5555/bank_simulation
    username: root
    password: audi51407088
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false 