server:
  port: 8081
  ssl:
    enabled: false
  http2:
    enabled: false

spring:
  application:
    name: transaction-producer
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false 